
export const ACTION_CHANGE_TAB = 'CHANGE_TAB'

export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'

export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS'

export const ACTION_LOGINING = 'ACTION_LOGINING'

export const ACTION_LOGIN_IN_INIT = 'ACTION_LOGIN_IN_INIT'

export const ACTION_GET_PICTURE_ID_LIST = 'ACTION_GET_PICTURE_ID_LIST'

export const ACTION_GET_PICTURE_DETAIL = 'ACTION_GET_PICTURE_DETAIL'









