
export const SETTING_PAGE = 'SETTING_PAGE';

export const LOGIN_PAGE = 'LOGIN_PAGE';

export const READING_CAROUSEL_DETAIL = 'READING_CAROUSEL_DETAIL';

export const READING_ESSAY_DETAIL = 'READING_ESSAY_DETAIL'

export const READING_SERIAL_DETAIL = 'READING_SERIAL_DETAIL'

export const READING_QUESTION_DETAIL = 'READING_QUESTION_DETAIL';

export const PERSONAL_CENTER = 'PERSONAL_CENTER';


